### ISSUE TITLE
msi failed for 1.17.0

### ISSUE THREAD

**Issue by phanirithvij** [dolthub/windows-msi-creator#25]
https://github.com/dolthub/windows-msi-creator/actions/runs/6343913497/job/17232854994#step:3:8
Could you re-run workflow manually in this repo again @fulghum?

cc: @macneale4

**Comment by fulghum** [comment]
Looks like we hit a transient issue with calling out to Docker. I just restarted the workflow and will keep an eye on it.

**Comment by fulghum** [comment]
Workflow completed the second time around. Thank you for noticing this and pinging us about it! 🙏
